language: node_js
install:
  - yarn
node_js:
  - "stable"
cache:
  directories:
    - "$HOME/.yarn-cache"
script:
  - yarn test
  - NODE_ENV=production yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  site_url: https://zmgalante.github.io/lletter6/
  on:
    branch: master