language: node_js
install:
  - yarn
node_js:
  - 'stable'
addons:
  apt:
    packages:
      # needed by Cypress, not in Ubuntu 16+ by default
      - libgconf-2-4
cache:
  directories:
    - '$HOME/.yarn-cache'
    - '$HOME/travis/.cache/Cypress'
script:
  - cypress install
  - yarn test:full
  - NODE_ENV=production yarn build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  site_url: https://zmgalante.github.io/lletter6/
  on:
    branch: master
